repositories:
  Leap:
    project: openSUSE:Leap:15.3
    repository: standard
  Uyuni_Other:
    project: systemsmanagement:Uyuni:Master:Other
    repository: openSUSE_Leap_15.3
  Uyuni:
    project: systemsmanagement:Uyuni:Master
    repository: openSUSE_Leap_15.3
artifacts:
  - artifact: simple-core
    # How comes that package is not noarch?
    arch: x86_64
    repository: Uyuni_Other
  - artifact: lucene-core
    jar: lucene-core
    package: lucene
    repository: Uyuni_Other
  - artifact: lucene-analyzers
    jar: lucene-analyzers
    package: lucene
    repository: Uyuni_Other
  - artifact: commons-lang3
    package: apache-commons-lang3
    repository: Leap
  - artifact: commons-logging
    package: apache-commons-logging
    jar: apache-commons-logging\.jar
    repository: Leap
  - artifact: redstone-xmlrpc
    jar: redstone-xmlrpc-[0-9.]+
    repository: Uyuni_Other
  - artifact: mybatis
    package: apache-mybatis
    repository: Uyuni_Other
  - artifact: quartz
    repository: Uyuni_Other
  - artifact: log4j
    package: log4j12
    repository: Leap
  - artifact: c3p0
    repository: Uyuni_Other
  - artifact: mchange-commons-java
    package: mchange-commons
    repository: Uyuni_Other
  - artifact: picocontainer
    repository: Uyuni_Other
  - artifact: hadoop
    repository: Uyuni_Other
