url: http://download.suse.de/ibs
group: manager-50

repositories:
  15_SP2_Update:
    project: SUSE:SLE-15-SP2:Update
    repository: standard
  15_SP4_GA:
    project: SUSE:SLE-15-SP4:GA
    repository: standard
  50_GA:
    project: SUSE:SLE-15-SP6:Update:Products:Manager50
    repository: standard
  D_G_M_50:
    project: Devel:Galaxy:Manager:5.0
    repository: SLE_15_SP6
artifacts:
  - artifact: simple-core
    # How comes that package is not noarch?
    arch: x86_64
    repository: 50_GA
  - artifact: lucene-core
    jar: lucene-core
    package: lucene
    repository: 50_GA
  - artifact: lucene-analyzers
    jar: lucene-analyzers
    package: lucene
    repository: 50_GA
  - artifact: commons-lang3
    package: apache-commons-lang3
    repository: 15_SP2_Update
  - artifact: commons-logging
    package: apache-commons-logging
    jar: apache-commons-logging\.jar
    repository: 15_SP2_Update
  - artifact: redstone-xmlrpc
    jar: redstone-xmlrpc-[0-9.]+
    repository: 50_GA
  - artifact: mybatis
    package: mybatis
    repository: 15_SP2_Update
  - artifact: quartz
    repository: 50_GA
  - artifact: log4j-core
    jar: log4j-core.jar
    package: log4j
    repository: 15_SP2_Update
  - artifact: log4j-api
    jar: log4j-api.jar
    package: log4j
    repository: 15_SP2_Update
  - artifact: c3p0
    repository: 15_SP4_GA
  - artifact: mchange-commons-java
    package: mchange-commons
    repository: 15_SP4_GA
  - artifact: picocontainer
    repository: 50_GA

