version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web/html/src"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
    # This is currently bugged, see https://github.com/dependabot/dependabot-core/issues/2521
    allow:
      - dependency-type: "production"

  - package-ecosystem: "github-actions" # Check for updates to GitHub Actions every weekday
    directory: "/"
    schedule: 
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]  # Ignore patch updates
