# SPDX-FileCopyrightText: 2025 SUSE LLC
#
# SPDX-License-Identifier: Apache-2.0
version = 1
SPDX-PackageName = "uyuni"
SPDX-PackageSupplier = "Uyuni Project <>"
SPDX-PackageDownloadLocation = "https://github.com/uyuni-project/uyuni"

[[annotations]]
path = ["web/html/src/branding/fonts/Lato/*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2010-2014 tyPoland Lukasz Dziedzic <team@latofonts.com>"
SPDX-License-Identifier = "OFL-1.1-RFN"

[[annotations]]
path = ["web/html/src/branding/fonts/SUSE/*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 The SUSE Project Authors"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = ["web/html/src/branding/fonts/WorkSans/*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 The Work Sans Project Authors"
SPDX-License-Identifier = "OFL-1.1"
