default: -f pretty -r features --publish-quiet
action_chains: --tags @scope_action_chains
ansible: --tags @scope_ansible
building_container_images: --tags @scope_building_container_images
centos: --tags @centos_minion
changing_software_channels: --tags @scope_changing_software_channels
cobbler: --tags @scope_cobbler
configuration_channels: --tags @scope_configuration_channels
content_lifecycle_management: --tags @scope_content_lifecycle_management
content_staging: --tags @scope_content_staging
cve_audit: --tags @scope_cve_audit
formulas: --tags @scope_formulas
hub: --tags @scope_hub
kubernetes_integration: --tags @scope_kubernetes_integration
maintenance_windows: --tags @scope_maintenance_windows
monitoring: --tags @scope_monitoring
notification_message: --tags @scope_notification_message
onboarding: --tags @scope_onboarding
openscap: --tags @scope_openscap
power_management: --tags @scope_power_management
proxy: --tags @scope_proxy
recurring_actions: --tags @scope_recurring_actions
reportdb: --tags @scope_reportdb
res: --tags @scope_res
retail: --tags @scope_retail
retracted_patches: --tags @scope_retracted_patches
salt_ssh: --tags @scope_salt_ssh
salt: --tags @scope_salt
smdba: --tags @scope_smdba
spacecmd: --tags @scope_spacecmd
spacewalk_utils: --tags @scope_spacewalk_utils
sp_migration: --tags @scope_sp_migration
subscription_matching: --tags @scope_subscription_matching
sumatoolbox: --tags @scope_sumatoolbox
tomcat: --tags @scope_tomcat
traditional_client: --tags @scope_traditional_client
ubuntu: --tags @scope_ubuntu
virtual_host_manager: --tags @scope_virtual_host_manager
virtualization: --tags @scope_virtualization
visualization: --tags @scope_visualization
xmlrpc: --tags @scope_xmlrpc
