repositories:
  Leap:
    project: openSUSE:Leap:15.6
    repository: standard
  Uyuni_Other:
    project: systemsmanagement:Uyuni:Master:Other
    repository: openSUSE_Leap_15.6
  Uyuni:
    project: systemsmanagement:Uyuni:Master
    repository: openSUSE_Leap_15.6
  Leap_sle:
    url: https://download.opensuse.org/update/leap/15.6/sle
artifacts:
  - artifact: asm
    package: objectweb-asm
    jar: asm-all
    repository: Leap_sle
  - artifact: antlr
    package: antlr-java
    repository: Leap
  - artifact: bcel
    repository: Leap_sle
  - artifact: byte-buddy
    package: byte-buddy
    repository: Leap_sle
    jar: byte-buddy\.jar
  - artifact: byte-buddy-dep
    package: byte-buddy
    repository: Leap_sle
    jar: byte-buddy-dep\.jar
  - artifact: c3p0
    repository: Leap
  - artifact: classmate
    repository: Leap
  - artifact: javax.mail
    jar: javax\.mail\.jar
    package: javamail
    repository: Leap_sle
  - artifact: commons-beanutils
    package: apache-commons-beanutils
    repository: Leap_sle
  - artifact: commons-cli
    package: apache-commons-cli
    repository: Leap
  - artifact: commons-codec
    package: apache-commons-codec
    repository: Leap
  - artifact: commons-collections
    package: apache-commons-collections
    repository: Leap
  - artifact: commons-digester
    package: apache-commons-digester
    repository: Leap
  - artifact: commons-discovery
    package: jakarta-commons-discovery
    repository: Leap
  - artifact: commons-fileupload2-core
    package: apache-commons-fileupload2-core
    repository: Uyuni_Other
  - artifact: commons-fileupload2-javax
    package: apache-commons-fileupload2-javax
    repository: Uyuni_Other
  - artifact: commons-io
    package: apache-commons-io
    repository: Leap_sle
  - artifact: commons-jexl
    package: apache-commons-jexl
    jar: commons-jexl\.jar
    repository: Leap
  - artifact: commons-lang3
    package: apache-commons-lang3
    repository: Leap_sle
  - artifact: commons-text
    package: apache-commons-text
    repository: Leap_sle
  - artifact: commons-logging
    package: apache-commons-logging
    jar: apache-commons-logging\.jar
    repository: Leap_sle
  - artifact: commons-validator
    package: apache-commons-validator
    repository: Leap
  - artifact: commons-compress
    package: apache-commons-compress
    repository: Leap
  - artifact: concurrentlinkedhashmap-lru
    repository: Leap
  - artifact: dom4j
    repository: Leap_sle
  - artifact: ehcache-core
    package: ehcache
    repository: Uyuni_Other
  - artifact: geronimo-jta_1.1_spec
    package: geronimo-jta-1_1-api
    repository: Leap
  - artifact: gson
    package: google-gson
    jar: gson\.jar
    repository: Leap
  - artifact: hibernate-c3p0
    package: hibernate5-c3p0
    jar: hibernate-c3p0
    repository: Uyuni_Other
  - artifact: hibernate-types-52
    package: hibernate-types
    repository: Uyuni_Other
  - artifact: jackson-annotations
    repository: Leap_sle
  - artifact: jackson-core
    repository: Leap_sle
  - artifact: jackson-databind
    repository: Leap_sle
  - artifact: hibernate-commons-annotations
    repository: Uyuni_Other
  - artifact: hibernate-core
    package: hibernate5-core
    repository: Uyuni_Other
  - artifact: hibernate-ehcache
    package: hibernate5-ehcache
    repository: Uyuni_Other
  - artifact: httpasyncclient
    package: httpcomponents-asyncclient
    jar: httpasyncclient-[0-9.]+
    repository: Leap
  - artifact: httpclient
    package: httpcomponents-client
    repository: Leap_sle
  - artifact: httpcore
    package: httpcomponents-core
    jar: httpcore\.jar
    repository: Leap_sle
  - artifact: httpcore-nio
    package: httpcomponents-core
    repository: Leap_sle
  - artifact: jade4j
    repository: Uyuni_Other
  - artifact: jakarta.persistence-api
    package: jpa-api
    repository: Uyuni_Other
  - artifact: java-saml
    jar: java-saml-[0-9.]+
    repository: Uyuni_Other
  - artifact: java-saml-core
    package: java-saml
    repository: Uyuni_Other
  - artifact: javassist
    repository: Leap
  - artifact: jboss-logging
    repository: Leap
  - artifact: jctools-core
    package: jctools
    repository: Leap_sle
  - artifact: jdom
    repository: Leap
  - artifact: joda-time
    repository: Leap
  - artifact: jose4j
    repository: Uyuni_Other
  - artifact: log4j-core
    package: log4j
    repository: Leap
  - artifact: log4j-api
    package: log4j
    repository: Leap
  - artifact: log4j-slf4j-impl
    package: log4j-slf4j
    repository: Leap
  - artifact: jsch
    repository: Leap_sle
  - artifact: mchange-commons-java
    package: mchange-commons
    repository: Leap
  - artifact: netty-buffer
    package: netty
    repository: Leap_sle
  - artifact: netty-codec
    package: netty
    jar: netty-codec\.jar
    repository: Leap_sle
  - artifact: netty-common
    package: netty
    repository: Leap_sle
  - artifact: netty-handler
    package: netty
    jar: netty-handler\.jar
    repository: Leap_sle
  - artifact: netty-resolver
    package: netty
    jar: netty-resolver\.jar
    repository: Leap_sle
  - artifact: netty-transport
    package: netty
    jar: netty-transport\.jar
    repository: Leap_sle
  - artifact: netty-transport-native-unix-common
    package: netty
    jar: netty-transport-native-unix-common\.jar
    repository: Leap_sle
  - artifact: netty-transport-native-unix-common-linux-x86_64
    package: netty
    repository: Leap_sle
  - artifact: client
    package: ongres-scram-client
    repository: Leap
  - artifact: common
    package: ongres-scram
    repository: Leap
  - artifact: stringprep
    package: ongres-stringprep
    repository: Leap
  - artifact: saslprep
    package: ongres-stringprep-saslprep
    repository: Leap
  - artifact: oro
    repository: Leap
  - artifact: pgjdbc-ng
    repository: Uyuni_Other
  - artifact: postgresql
    package: postgresql-jdbc
    repository: Leap
  - artifact: quartz
    repository: Uyuni_Other
  - artifact: redstone-xmlrpc
    jar: redstone-xmlrpc-[0-9.]+
    repository: Uyuni_Other
  - artifact: redstone-xmlrpc-client
    package: redstone-xmlrpc
    repository: Uyuni_Other
  - artifact: salt-netapi-client
    repository: Uyuni
  - artifact: simpleclient
    package: prometheus-simpleclient-java
    jar: simpleclient-[0-9.]+
    repository: Uyuni_Other
  - artifact: simpleclient_common
    package: prometheus-simpleclient-java
    repository: Uyuni_Other
  - artifact: simpleclient_hibernate
    package: prometheus-simpleclient-java
    repository: Uyuni_Other
  - artifact: simpleclient_httpserver
    package: prometheus-simpleclient-java
    repository: Uyuni_Other
  - artifact: simpleclient_servlet
    package: prometheus-simpleclient-java
    repository: Uyuni_Other
  - artifact: simple-core
    # How comes that package is not noarch?
    arch: x86_64
    repository: Uyuni_Other
  - artifact: simple-xml
    package: simplexml
    jar: simplexml\.jar
    repository: Uyuni_Other
  - artifact: sitemesh
    repository: Uyuni_Other
  - artifact: slf4j-api
    package: slf4j
    jar: api
    repository: Leap
  - artifact: snakeyaml
    repository: Leap_sle
  - artifact: spark-core
    package: spark-core
    repository: Uyuni_Other
  - artifact: spark-template-jade
    repository: Uyuni_Other
  - artifact: spy
    package: pgjdbc-ng
    repository: Uyuni_Other
  - artifact: statistics
    repository: Uyuni_Other
  - artifact: stax2-api
    package: woodstox
    repository: Uyuni_Other
  - artifact: struts
    repository: Uyuni_Other
  - artifact: taglibs-standard-impl
    package: tomcat-taglibs-standard-1_2_5
    repository: Uyuni_Other
  - artifact: taglibs-standard-jstlel
    package: tomcat-taglibs-standard-1_2_5
    repository: Uyuni_Other
  - artifact: taglibs-standard-spec
    package: tomcat-taglibs-standard-1_2_5
    repository: Uyuni_Other
  - artifact: woodstox-core-asl
    package: woodstox
    repository: Uyuni_Other
  - artifact: xalan
    package: xalan-j2
    jar: xalan-j2\.jar
    repository: Leap_sle
  - artifact: serializer
    package: xalan-j2
    jar: xalan-j2-serializer\.jar
    repository: Leap_sle
  - artifact: xercesImpl
    package: xerces-j2
    repository: Leap
  - artifact: xmlsec
    repository: Uyuni_Other
  - artifact: velocity-engine-core
    repository: Leap_sle

  - artifact: tomcat-el-api
    package: tomcat-el-3_0-api
    repository: Leap
  - artifact: tomcat-jsp-api
    package: tomcat-jsp-2_3-api
    repository: Leap
  - artifact: tomcat-juli
    package: tomcat-lib
    repository: Leap
  - artifact: tomcat-servlet-api
    package: tomcat-servlet-4_0-api
    repository: Leap
  - artifact: tomcat-websocket-api
    jar: websocket-api\.jar
    package: tomcat-lib
    repository: Leap

  - artifact: hamcrest
    repository: Leap_sle
  - artifact: junit
    repository: Leap
  - artifact: ical4j
    repository: Uyuni_Other
  - artifact: jetty-util
    repository: Leap_sle
  - artifact: jaxb-api
    package: glassfish-jaxb-api
    repository: Leap
  - artifact: jaxb-runtime
    package: glassfish-jaxb-runtime
    repository: Leap
  - artifact: jaxb-impl
    package: glassfish-jaxb-runtime
    repository: Leap
  - artifact: txw2
    package: glassfish-jaxb-txw2
    repository: Leap
  - artifact: javax.activation
    package: glassfish-activation
    repository: Leap
  - artifact: istack-commons-runtime
    repository: Leap
  - artifact: stax-ex
    repository: Leap
