repositories:
  Leap:
    project: openSUSE:Leap:15.1
    repository: standard
  Uyuni_Other:
    project: systemsmanagement:Uyuni:Master:Other
    repository: openSUSE_Leap_15.1
  Uyuni:
    project: systemsmanagement:Uyuni:Master
    repository: openSUSE_Leap_15.1
artifacts:
  - artifact: asm
    package: asm3
    jar: asm3-all
    repository: Leap
  - artifact: antlr
    repository: Leap
  - artifact: bcel
    repository: Leap
  - artifact: byte-buddy
    repository: Uyuni_Other
  - artifact: c3p0
    repository: Uyuni_Other
  - artifact: cglib
    repository: Leap
  - artifact: classmate
    repository: Uyuni_Other
  - artifact: classpathx-mail-1.3.1-monolithic
    package: classpathx-mail
    jar: classpathx-mail-1.3.1-monolithic
    repository: Leap
  - artifact: commons-beanutils
    package: apache-commons-beanutils
    repository: Leap
  - artifact: commons-cli
    package: apache-commons-cli
    repository: Leap
  - artifact: commons-codec
    package: apache-commons-codec
    repository: Leap
  - artifact: commons-collections
    package: apache-commons-collections
    repository: Leap
  - artifact: commons-digester
    package: jakarta-commons-digester
    jar: jakarta-commons-digester-[0-9.]+\.jar
    repository: Leap
  - artifact: commons-discovery
    package: jakarta-commons-discovery
    repository: Leap
  - artifact: commons-el
    package: jakarta-commons-el
    repository: Uyuni_Other
  - artifact: commons-fileupload
    package: jakarta-commons-fileupload
    repository: Leap
  - artifact: commons-io
    package: apache-commons-io
    repository: Leap
  - artifact: commons-jexl
    package: apache-commons-jexl
    repository: Uyuni_Other
  - artifact: commons-lang3
    package: apache-commons-lang3
    repository: Leap
  - artifact: commons-logging
    package: apache-commons-logging
    jar: apache-commons-logging\.jar
    repository: Leap
  - artifact: commons-validator
    package: apache-commons-validator
    repository: Leap
  - artifact: concurrent
    repository: Uyuni_Other
  - artifact: concurrentlinkedhashmap-lru
    repository: Uyuni_Other
  - artifact: dom4j
    jar: dom4j-[0-9.]+
    repository: Leap
  - artifact: dwr
    repository: Uyuni_Other
  - artifact: ehcache-core
    package: ehcache
    repository: Uyuni_Other
  - artifact: geronimo-jta-1.1-api
    package: geronimo-specs
    rpm: geronimo-jta-1_1
    repository: Leap
  - artifact: google-gson
    repository: Uyuni_Other
  - artifact: hibernate-c3p0
    package: hibernate5
    jar: hibernate-c3p0
    repository: Uyuni_Other
  - artifact: hibernate-commons-annotations
    repository: Uyuni_Other
  - artifact: hibernate-core
    package: hibernate5
    jar: hibernate-core
    repository: Uyuni_Other
  - artifact: hibernate-ehcache
    package: hibernate5
    jar: hibernate-ehcache
    repository: Uyuni_Other
  - artifact: httpasyncclient
    package: httpcomponents-asyncclient
    jar: httpasyncclient-[0-9.]+
    repository: Uyuni_Other
  - artifact: httpclient
    package: httpcomponents-client
    jar: httpclient-[0-9.]+
    repository: Uyuni_Other
  - artifact: httpcore
    package: httpcomponents-core
    jar: httpcore-[0-9.]+
    repository: Uyuni_Other
  - artifact: httpcore-nio
    package: httpcomponents-core
    jar: httpcore-nio
    repository: Uyuni_Other
  - artifact: jade4j
    repository: Uyuni_Other
  - artifact: jaf
    package: gnu-jaf
    repository: Leap
  - artifact: jakarta-persistence-api
    package: jpa-api
    repository: Uyuni_Other
  - artifact: java-saml
    jar: java-saml-[0-9.]+
    repository: Uyuni_Other
  - artifact: java-saml-core
    package: java-saml
    jar: java-saml-core
    repository: Uyuni_Other
  - artifact: javassist
    repository: Uyuni_Other
  - artifact: jboss-logging
    repository: Uyuni_Other
  - artifact: jcommon
    repository: Uyuni_Other
  - artifact: jdom
    rpm: jdom
    repository: Leap
  - artifact: joda-time
    repository: Uyuni_Other
  - artifact: jose4j
    repository: Uyuni_Other
  - artifact: log4j
    repository: Leap
  - artifact: jsch
    repository: Uyuni_Other
  - artifact: netty-buffer
    package: netty
    jar: netty-buffer
    repository: Uyuni_Other
  - artifact: netty-codec
    package: netty
    jar: netty-codec
    repository: Uyuni_Other
  - artifact: netty-common
    package: netty
    jar: netty-common
    repository: Uyuni_Other
  - artifact: netty-handler
    package: netty
    jar: netty-handler
    repository: Uyuni_Other
  - artifact: netty-resolver
    package: netty
    jar: netty-resolver
    repository: Uyuni_Other
  - artifact: netty-transport
    package: netty
    jar: netty-transport
    repository: Uyuni_Other
  - artifact: netty-transport-native-unix-common
    package: netty
    jar: netty-transport-native-unix-common
    repository: Uyuni_Other
  - artifact: oro
    repository: Leap
  - artifact: pgjdbc-ng
    jar: pgjdbc-ng
    repository: Uyuni_Other
  - artifact: postgresql-jdbc
    repository: Uyuni_Other
  - artifact: quartz
    repository: Uyuni
  - artifact: redstone-xmlrpc
    jar: redstone-xmlrpc-[0-9.]+
    repository: Uyuni_Other
  - artifact: redstone-xmlrpc-client
    package: redstone-xmlrpc
    jar: redstone-xmlrpc-client
    repository: Uyuni_Other
  - artifact: salt-netapi-client
    repository: Uyuni
  - artifact: simpleclient
    package: prometheus-client-java
    jar: simpleclient-[0-9.]+
    repository: Uyuni_Other
  - artifact: simpleclient_common
    package: prometheus-client-java
    jar: simpleclient_common
    repository: Uyuni_Other
  - artifact: simpleclient_httpserver
    package: prometheus-client-java
    jar: simpleclient_httpserver
    repository: Uyuni_Other
  - artifact: simpleclient_servlet
    package: prometheus-client-java
    jar: simpleclient_servlet
    repository: Uyuni_Other
  - artifact: simple-core
    # How comes that package is not noarch?
    arch: x86_64
    jar: simple-core
    repository: Uyuni_Other
  - artifact: simple-xml
    repository: Uyuni_Other
  - artifact: sitemesh
    repository: Uyuni_Other
  - artifact: slf4j-api
    package: slf4j
    jar: api
    repository: Leap
  - artifact: slf4j-log4j12
    package: slf4j
    jar: log4j12
    repository: Leap
  - artifact: snakeyaml
    repository: Uyuni_Other
  - artifact: spark-core
    repository: Uyuni_Other
  - artifact: spark-template-jade
    repository: Uyuni_Other
  - artifact: spy
    package: pgjdbc-ng
    jar: spy
    repository: Uyuni_Other
  - artifact: statistics
    repository: Uyuni_Other
  - artifact: stax-api
    package: woodstox
    jar: stax-api
    repository: Uyuni_Other
  - artifact: stax2-api
    package: woodstox
    jar: stax2-api
    repository: Uyuni_Other
  - artifact: stringtree-json
    repository: Uyuni_Other
  - artifact: struts
    rpm: struts-[0-9.]+
    repository: Uyuni_Other
  - artifact: taglibs-standard-impl
    package: tomcat-taglibs-standard-1_2_5
    jar: taglibs-standard-impl
    repository: Uyuni_Other
  - artifact: taglibs-standard-jstlel
    package: tomcat-taglibs-standard-1_2_5
    jar: taglibs-standard-jstlel
    repository: Uyuni_Other
  - artifact: taglibs-standard-spec
    package: tomcat-taglibs-standard-1_2_5
    jar: taglibs-standard-spec
    repository: Uyuni_Other
  - artifact: woodstox-core-asl
    package: woodstox
    jar: woodstox-core-asl
    repository: Uyuni_Other
  - artifact: xalan-j2
    rpm: xalan-j2-[0-9.]+
    jar: xalan-j2-[0-9.]+
    repository: Leap
  - artifact: xalan-j2-serializer
    package: xalan-j2
    rpm: xalan-j2-[0-9.]+
    jar: xalan-j2-serializer
    repository: Leap
  - artifact: xerces-j2
    rpm: xerces-j2-[0-9.]+
    jar: xerces-j2-[0-9.]+
    repository: Leap
  - artifact: xmlsec
    repository: Uyuni_Other
  - artifact: commons-lang
    package: apache-commons-lang
    repository: Leap
  - artifact: velocity
    repository: Uyuni_Other

  - artifact: jasper
    package: tomcat
    rpm: tomcat-lib
    jar: jasper\.jar
    repository: Leap
  - artifact: jasper-el
    package: tomcat
    rpm: tomcat-lib
    jar: jasper-el
    repository: Leap
  - artifact: tomcat-el-3.0-api
    package: tomcat
    rpm: tomcat-el-3_0-api
    jar: tomcat-el-3.0-api
    repository: Leap
  - artifact: tomcat-jsp-2.3-api
    package: tomcat
    rpm: tomcat-jsp-2_3-api
    repository: Leap
  - artifact: tomcat-juli
    package: tomcat
    rpm: tomcat-lib
    jar: tomcat-juli
    repository: Leap
  - artifact: tomcat-servlet-4.0-api
    package: tomcat
    rpm: tomcat-servlet-4_0-api
    repository: Leap

  - artifact: hamcrest-core
    package: hamcrest
    jar: hamcrest/core
    repository: Leap
  - artifact: hamcrest-library
    package: hamcrest
    jar: hamcrest/library
    repository: Leap
