repositories:
  Leap:
    project: openSUSE:Leap:15.6
    repository: standard
  Uyuni_Other:
    project: systemsmanagement:Uyuni:Master:Other
    repository: openSUSE_Leap_15.6
  Uyuni:
    project: systemsmanagement:Uyuni:Master
    repository: openSUSE_Leap_15.6
  Leap_sle:
    url: https://download.opensuse.org/update/leap/15.6/sle
  Uyuni_Jakarta:
    project: systemsmanagement:Uyuni:Master:jakarta
    repository: openSUSE_Leap_15.6
artifacts:
  - artifact: asm
    package: objectweb-asm
    jar: asm-all
    repository: Uyuni_Jakarta
  - artifact: antlr4-runtime
    package: antlr4-java
    repository: Uyuni_Jakarta
  - artifact: bcel
    repository: Leap_sle
  - artifact: byte-buddy
    package: byte-buddy
    repository: Uyuni_Jakarta
    jar: byte-buddy\.jar
  - artifact: c3p0
    repository: Leap
  - artifact: cglib
    jar: cglib\.jar
    repository: Leap
  - artifact: classmate
    repository: Leap
  - artifact: jakarta.mail-api
    package: jakarta-mail
    repository: Uyuni_Jakarta
  - artifact: jakarta.mail
    package: angus-mail-core
    repository: Uyuni_Jakarta
  - artifact: commons-beanutils
    package: apache-commons-beanutils
    repository: Leap_sle
  - artifact: commons-cli
    package: apache-commons-cli
    repository: Leap
  - artifact: commons-codec
    package: apache-commons-codec
    repository: Leap
  - artifact: commons-collections
    package: apache-commons-collections
    repository: Leap
  - artifact: commons-digester
    package: apache-commons-digester
    repository: Leap
  - artifact: commons-discovery
    package: jakarta-commons-discovery
    repository: Leap
  - artifact: commons-fileupload2-core
    package: apache-commons-fileupload2-core
    repository: Uyuni_Other
  - artifact: apache-commons-fileupload2-jakarta-servlet6
    package: apache-commons-fileupload2-jakarta-servlet6
    repository: Uyuni_Other
  - artifact: commons-io
    package: apache-commons-io
    repository: Leap_sle
  - artifact: commons-jexl
    package: apache-commons-jexl
    jar: commons-jexl\.jar
    repository: Leap
  - artifact: commons-lang3
    package: apache-commons-lang3
    repository: Leap_sle
  - artifact: commons-text
    package: apache-commons-text
    repository: Leap_sle
  - artifact: commons-logging
    package: apache-commons-logging
    jar: apache-commons-logging\.jar
    repository: Leap_sle
  - artifact: commons-validator
    package: apache-commons-validator
    repository: Leap
  - artifact: commons-compress
    package: apache-commons-compress
    repository: Leap
  - artifact: concurrentlinkedhashmap-lru
    repository: Leap
  - artifact: dom4j
    repository: Leap_sle
  - artifact: jcache
    package: jcache
    repository: Uyuni_Jakarta
  - artifact: geronimo-jta_1.1_spec
    package: geronimo-jta-1_1-api
    repository: Leap
  - artifact: gson
    package: google-gson
    jar: gson\.jar
    repository: Leap
  - artifact: hibernate-c3p0
    package: hibernate-c3p0
    jar: hibernate-c3p0
    repository: Uyuni_Jakarta
  - artifact: hypersistence-utils-hibernate-71
    package: hypersistence-utils-hibernate-71
    repository: Uyuni_Jakarta
  - artifact: jackson-annotations
    repository: Leap_sle
  - artifact: jackson-core
    repository: Leap_sle
  - artifact: jackson-databind
    repository: Leap_sle
  - artifact: hibernate-models
    package: hibernate-models
    repository: Uyuni_Jakarta
  - artifact: hibernate-core
    package: hibernate-core
    repository: Uyuni_Jakarta
  - artifact: hibernate-jcache
    package: hibernate-jcache
    repository: Uyuni_Jakarta
  - artifact: httpasyncclient
    package: httpcomponents-asyncclient
    jar: httpasyncclient-[0-9.]+
    repository: Leap
  - artifact: httpclient
    package: httpcomponents-client
    repository: Leap_sle
  - artifact: httpcore
    package: httpcomponents-core
    jar: httpcore\.jar
    repository: Leap_sle
  - artifact: httpcore-nio
    package: httpcomponents-core
    repository: Leap_sle
  - artifact: jade4j
    repository: Uyuni_Other
  - artifact: jakarta-persistence-api
    jar: jakarta.persistence-api.jar
    repository: Uyuni_Jakarta
  - artifact: java-saml
    jar: java-saml-[0-9.]+
    repository: Uyuni_Jakarta
  - artifact: java-saml-core
    package: java-saml
    repository: Uyuni_Jakarta
  - artifact: javassist
    repository: Leap
  - artifact: jboss-logging
    repository: Uyuni_Jakarta
  - artifact: jctools-core
    package: jctools
    repository: Leap_sle
  - artifact: jdom
    repository: Leap
  - artifact: joda-time
    repository: Leap
  - artifact: jose4j
    repository: Uyuni_Other
  - artifact: log4j-core
    package: log4j
    repository: Leap
  - artifact: log4j-api
    package: log4j
    repository: Leap
  - artifact: log4j-slf4j-impl
    package: log4j-slf4j
    repository: Leap
  - artifact: jsch
    repository: Leap_sle
  - artifact: mchange-commons-java
    package: mchange-commons
    repository: Leap
  - artifact: netty-buffer
    package: netty
    repository: Leap_sle
  - artifact: netty-codec
    package: netty
    jar: netty-codec\.jar
    repository: Leap_sle
  - artifact: netty-common
    package: netty
    repository: Leap_sle
  - artifact: netty-handler
    package: netty
    jar: netty-handler\.jar
    repository: Leap_sle
  - artifact: netty-resolver
    package: netty
    jar: netty-resolver\.jar
    repository: Leap_sle
  - artifact: netty-transport
    package: netty
    jar: netty-transport\.jar
    repository: Leap_sle
  - artifact: netty-transport-native-unix-common
    package: netty
    jar: netty-transport-native-unix-common\.jar
    repository: Leap_sle
  - artifact: netty-transport-native-unix-common-linux-x86_64
    package: netty
    repository: Leap_sle
  - artifact: client
    package: ongres-scram-client
    repository: Leap
  - artifact: common
    package: ongres-scram
    repository: Leap
  - artifact: stringprep
    package: ongres-stringprep
    repository: Leap
  - artifact: saslprep
    package: ongres-stringprep-saslprep
    repository: Leap
  - artifact: oro
    repository: Leap
  - artifact: pgjdbc-ng
    repository: Uyuni_Other
  - artifact: postgresql
    package: postgresql-jdbc
    repository: Leap
  - artifact: quartz
    repository: Uyuni_Jakarta
  - artifact: redstone-xmlrpc
    jar: redstone-xmlrpc-[0-9.]+
    repository: Uyuni_Jakarta
  - artifact: redstone-xmlrpc-client
    package: redstone-xmlrpc
    repository: Uyuni_Jakarta
  - artifact: salt-netapi-client
    repository: Uyuni_Jakarta
  - artifact: simpleclient
    package: prometheus-simpleclient-java
    jar: simpleclient-[0-9.]+
    repository: Uyuni_Other
  - artifact: simpleclient_common
    package: prometheus-simpleclient-java
    repository: Uyuni_Other
  - artifact: simpleclient_hibernate
    package: prometheus-simpleclient-java
    repository: Uyuni_Other
  - artifact: simpleclient_httpserver
    package: prometheus-simpleclient-java
    repository: Uyuni_Other
  - artifact: simpleclient_servlet
    package: prometheus-simpleclient-java
    repository: Uyuni_Other
  - artifact: simple-core
    # How comes that package is not noarch?
    arch: x86_64
    repository: Uyuni_Other
  - artifact: simplexml
    jar: simplexml\.jar
    repository: Uyuni_Other
  - artifact: sitemesh
    repository: Uyuni_Jakarta
  - artifact: slf4j-api
    package: slf4j
    jar: api
    repository: Leap
  - artifact: snakeyaml
    repository: Leap_sle
  - artifact: spark-core
    package: spark-core
    repository: Uyuni_Jakarta
  - artifact: spark-template-jade
    repository: Uyuni_Other
  - artifact: spy
    package: pgjdbc-ng
    repository: Uyuni_Other
  - artifact: statistics
    repository: Uyuni_Other
  - artifact: stax2-api
    package: woodstox
    repository: Uyuni_Other
  - artifact: struts
    repository: Uyuni_Jakarta
  - artifact: taglibs-standard-impl
    package: tomcat-taglibs-standard-1_2_5
    repository: Uyuni_Other
  - artifact: taglibs-standard-jstlel
    package: tomcat-taglibs-standard-1_2_5
    repository: Uyuni_Other
  - artifact: taglibs-standard-spec
    package: tomcat-taglibs-standard-1_2_5
    repository: Uyuni_Other
  - artifact: woodstox-core-asl
    package: woodstox
    repository: Uyuni_Other
  - artifact: xalan
    package: xalan-j2
    jar: xalan-j2\.jar
    repository: Leap_sle
  - artifact: serializer
    package: xalan-j2
    jar: xalan-j2-serializer\.jar
    repository: Leap_sle
  - artifact: xercesImpl
    package: xerces-j2
    repository: Leap
  - artifact: xmlsec
    repository: Uyuni_Other
  - artifact: velocity-engine-core
    repository: Leap_sle

  - artifact: tomcat-el-api
    package: tomcat11-el-6_0-api
    repository: Uyuni_Jakarta
  - artifact: tomcat-jsp-api
    package: tomcat11-jsp-4_0-api
    repository: Uyuni_Jakarta
  - artifact: tomcat-juli
    package: tomcat11-lib
    repository: Uyuni_Jakarta
  - artifact: tomcat-servlet-api
    package: tomcat11-servlet-6_1-api
    repository: Uyuni_Jakarta

  - artifact: hamcrest-core
    repository: Leap

  - artifact: hamcrest
    repository: Leap_sle
  - artifact: junit
    repository: Leap
  - artifact: ical4j
    repository: Uyuni_Other
  - artifact: jetty-util
    repository: Leap_sle
  - artifact: jakarta.xml.bind-api
    package: jaxb-api
    repository: Uyuni_Jakarta
  - artifact: jaxb-core
    package: jaxb-core
    repository: Uyuni_Jakarta
  - artifact: jaxb-runtime
    package: jaxb-runtime
    repository: Uyuni_Jakarta
  - artifact: txw2
    package: jaxb-txw2
    repository: Uyuni_Jakarta
  - artifact: jakarta.activation-api
    package: jakarta-activation
    repository: Uyuni_Jakarta
  - artifact: angus-activation
    package: angus-activation
    jar: angus-activation.jar
    repository: Uyuni_Jakarta
  - artifact: istack-commons-runtime
    repository: Leap
  - artifact: stax-ex
    repository: Leap 
  - artifact: jakarta.websocket-api
    package: jakarta-websocket
    repository: Uyuni_Jakarta
  - artifact: jakarta.inject-api
    package: jakarta-transactions
    repository: Uyuni_Jakarta
  - artifact: jakarta.transaction-api
    package: jakarta-transactions
    repository: Uyuni_Jakarta
  - artifact: jakarta.servlet.jsp.jstl
    package: jakarta-jstl
    jar: jakarta.servlet.jsp.jstl.jar
    repository: Uyuni_Jakarta
  - artifact: jakarta.servlet.jsp.jstl-api
    package: jakarta-jstl
    jar: jakarta.servlet.jsp.jstl-api.jar
    repository: Uyuni_Jakarta
