repositories:
  Leap:
    project: openSUSE:Leap:15.5
    repository: standard
  Uyuni_Other:
    project: systemsmanagement:Uyuni:Master:Other
    repository: openSUSE_Leap_15.5
  Uyuni:
    project: systemsmanagement:Uyuni:Master
    repository: openSUSE_Leap_15.5
  Leap_sle:
    url: https://download.opensuse.org/update/leap/15.5/sle
artifacts:
  - artifact: asm
    package: objectweb-asm
    jar: asm-all
    repository: Uyuni_Other
  - artifact: antlr
    package: antlr-java
    repository: Leap
  - artifact: bcel
    repository: Leap
  - artifact: byte-buddy
    repository: Uyuni_Other
  - artifact: c3p0
    repository: Leap
  - artifact: cglib
    jar: cglib.jar
    repository: Leap
  - artifact: classmate
    repository: Uyuni_Other
  - artifact: javax.mail
    jar: javax.mail.jar
    package: javamail
    repository: Leap
  - artifact: commons-beanutils
    package: apache-commons-beanutils
    repository: Leap
  - artifact: commons-cli
    package: apache-commons-cli
    repository: Leap
  - artifact: commons-codec
    package: apache-commons-codec
    repository: Leap_sle
  - artifact: commons-collections
    package: apache-commons-collections
    repository: Leap
  - artifact: commons-digester
    package: apache-commons-digester
    repository: Leap
  - artifact: commons-discovery
    package: jakarta-commons-discovery
    repository: Leap_sle
  - artifact: commons-el
    package: apache-commons-el
    repository: Leap
  - artifact: commons-fileupload
    package: apache-commons-fileupload
    repository: Leap_sle
  - artifact: commons-io
    package: apache-commons-io
    repository: Leap_sle
  - artifact: commons-jexl
    package: apache-commons-jexl
    jar: commons-jexl\.jar
    repository: Leap_sle
  - artifact: commons-lang3
    package: apache-commons-lang3
    repository: Leap
  - artifact: commons-logging
    package: apache-commons-logging
    jar: apache-commons-logging\.jar
    repository: Leap
  - artifact: commons-validator
    package: apache-commons-validator
    repository: Leap
  - artifact: commons-compress
    package: apache-commons-compress
    repository: Leap_sle
  - artifact: concurrent
    repository: Uyuni_Other
  - artifact: concurrentlinkedhashmap-lru
    repository: Uyuni_Other
  - artifact: dom4j
    repository: Leap
  - artifact: ehcache-core
    package: ehcache
    repository: Uyuni_Other
  - artifact: geronimo-jta-1.1-api
    package: geronimo-jta-1_1-api
    repository: Leap
  - artifact: google-gson
    jar: gson.jar
    repository: Leap
  - artifact: hibernate-c3p0
    package: hibernate5-c3p0
    jar: hibernate-c3p0
    repository: Uyuni_Other
  - artifact: hibernate-types-52
    package: hibernate-types
    repository: Uyuni_Other
  - artifact: jackson-annotations
    repository: Leap_sle
  - artifact: jackson-core
    repository: Leap_sle
  - artifact: jackson-databind
    repository: Leap_sle
  - artifact: hibernate-commons-annotations
    repository: Uyuni_Other
  - artifact: hibernate-core
    package: hibernate5-core
    repository: Uyuni_Other
  - artifact: hibernate-ehcache
    package: hibernate5-ehcache
    repository: Uyuni_Other
  - artifact: httpasyncclient
    package: httpcomponents-asyncclient
    jar: httpasyncclient-[0-9.]+
    repository: Leap
  - artifact: httpclient
    package: httpcomponents-client
    repository: Leap
  - artifact: httpcore
    package: httpcomponents-core
    jar: httpcore.jar
    repository: Leap
  - artifact: httpcore-nio
    package: httpcomponents-core
    repository: Leap
  - artifact: jade4j
    repository: Uyuni_Other
  - artifact: jakarta-persistence-api
    package: jpa-api
    repository: Uyuni_Other
  - artifact: java-saml
    jar: java-saml-[0-9.]+
    repository: Uyuni_Other
  - artifact: java-saml-core
    package: java-saml
    repository: Uyuni_Other
  - artifact: javassist
    repository: Leap_sle
  - artifact: jboss-logging
    repository: Leap
  - artifact: jctools-core
    package: jctools
    repository: Leap
  - artifact: jdom
    repository: Leap
  - artifact: joda-time
    repository: Leap
  - artifact: jose4j
    repository: Uyuni_Other
  - artifact: log4j-core
    jar: log4j-core.jar
    package: log4j
    repository: Leap_sle
  - artifact: log4j-api
    jar: log4j-api.jar
    package: log4j
    repository: Leap_sle
  - artifact: log4j-slf4j-impl
    jar: log4j-slf4j-impl.jar
    package: log4j-slf4j
    repository: Leap_sle
  - artifact: jsch
    repository: Leap_sle
  - artifact: mchange-commons-java
    package: mchange-commons
    repository: Leap
  - artifact: netty-buffer
    package: netty
    repository: Leap_sle
  - artifact: netty-codec
    package: netty
    jar: netty-codec.jar
    repository: Leap_sle
  - artifact: netty-common
    package: netty
    repository: Leap_sle
  - artifact: netty-handler
    package: netty
    jar: netty-handler.jar
    repository: Leap_sle
  - artifact: netty-resolver
    package: netty
    jar: netty-resolver.jar
    repository: Leap_sle
  - artifact: netty-transport
    package: netty
    jar: netty-transport.jar
    repository: Leap_sle
  - artifact: netty-transport-native-unix-common
    package: netty
    jar: netty-transport-native-unix-common.jar
    repository: Leap_sle
  - artifact: netty-transport-native-unix-common-linux-x86_64
    package: netty
    repository: Leap_sle
  - artifact: client
    package: ongres-scram-client
    repository: Leap
  - artifact: common
    package: ongres-scram
    repository: Leap
  - artifact: stringprep
    package: ongres-stringprep
    repository: Leap
  - artifact: saslprep
    package: ongres-stringprep-saslprep
    repository: Leap
  - artifact: oro
    repository: Leap
  - artifact: pgjdbc-ng
    repository: Uyuni_Other
  - artifact: postgresql-jdbc
    repository: Leap
  - artifact: quartz
    repository: Uyuni_Other
  - artifact: redstone-xmlrpc
    jar: redstone-xmlrpc-[0-9.]+
    repository: Uyuni_Other
  - artifact: redstone-xmlrpc-client
    package: redstone-xmlrpc
    repository: Uyuni_Other
  - artifact: salt-netapi-client
    repository: Uyuni
  - artifact: simpleclient
    package: prometheus-client-java
    jar: simpleclient-[0-9.]+
    repository: Uyuni_Other
  - artifact: simpleclient_common
    package: prometheus-client-java
    repository: Uyuni_Other
  - artifact: simpleclient_hibernate
    package: prometheus-client-java
    repository: Uyuni_Other
  - artifact: simpleclient_httpserver
    package: prometheus-client-java
    repository: Uyuni_Other
  - artifact: simpleclient_servlet
    package: prometheus-client-java
    repository: Uyuni_Other
  - artifact: simple-core
    # How comes that package is not noarch?
    arch: x86_64
    repository: Uyuni_Other
  - artifact: simple-xml
    repository: Uyuni_Other
  - artifact: sitemesh
    repository: Uyuni_Other
  - artifact: slf4j-api
    package: slf4j
    jar: api
    repository: Leap
  - artifact: snakeyaml
    repository: Leap
  - artifact: spark-core
    repository: Uyuni_Other
  - artifact: spark-template-jade
    repository: Uyuni_Other
  - artifact: spy
    package: pgjdbc-ng
    repository: Uyuni_Other
  - artifact: statistics
    repository: Uyuni_Other
  - artifact: stax2-api
    package: woodstox
    repository: Uyuni_Other
  - artifact: stringtree-json
    repository: Uyuni_Other
  - artifact: struts
    repository: Uyuni_Other
  - artifact: taglibs-standard-impl
    package: tomcat-taglibs-standard-1_2_5
    repository: Uyuni_Other
  - artifact: taglibs-standard-jstlel
    package: tomcat-taglibs-standard-1_2_5
    repository: Uyuni_Other
  - artifact: taglibs-standard-spec
    package: tomcat-taglibs-standard-1_2_5
    repository: Uyuni_Other
  - artifact: woodstox-core-asl
    package: woodstox
    repository: Uyuni_Other
  - artifact: xalan-j2
    jar: xalan-j2.jar
    repository: Leap
  - artifact: xalan-j2-serializer
    package: xalan-j2
    repository: Leap
  - artifact: xerces-j2
    repository: Leap
  - artifact: xmlsec
    repository: Uyuni_Other
  - artifact: velocity-engine-core
    repository: Uyuni_Other

  - artifact: jasper
    package: tomcat-lib
    jar: jasper\.jar
    repository: Leap_sle
  - artifact: jasper-el
    package: tomcat-lib
    repository: Leap_sle
  - artifact: tomcat-el-3.0-api
    package: tomcat-el-3_0-api
    repository: Leap_sle
  - artifact: tomcat-jsp-2.3-api
    package: tomcat-jsp-2_3-api
    repository: Leap_sle
  - artifact: tomcat-juli
    package: tomcat-lib
    repository: Leap_sle
  - artifact: tomcat-servlet-4.0-api
    package: tomcat-servlet-4_0-api
    repository: Leap_sle

  - artifact: hamcrest-core
    repository: Leap
  - artifact: hamcrest-library
    package: hamcrest
    jar: hamcrest/library
    repository: Leap
  - artifact: junit
    repository: Leap
  - artifact: ical4j
    repository: Uyuni_Other
  - artifact: jetty-util
    repository: Leap_sle
  - artifact: glassfish-jaxb-api
    repository: Uyuni_Other
  - artifact: jaxb-runtime
    package: glassfish-jaxb-runtime
    repository: Uyuni_Other
  - artifact: jaxb-impl
    package: glassfish-jaxb-runtime
    repository: Uyuni_Other
  - artifact: txw2
    package: glassfish-jaxb-txw2
    repository: Uyuni_Other
  - artifact: glassfish-activation
    repository: Uyuni_Other
  - artifact: istack-commons-runtime
    repository: Uyuni_Other
  - artifact: stax-ex
    repository: Uyuni_Other
