apiVersion: v1
kind: Service
metadata:
  name: uyuni-proxy-tcp
  namespace: "{{ .Values.namespace }}"
{{- if .Values.services.annotations }}
  annotations:
{{ toYaml .Values.services.annotations | indent 4 }}
{{- end }}
spec:
  selector:
    app: uyuni-proxy
  type: {{ .Values.services.type }}
  ports:
    - name: http
      port: 80
{{- if eq .Values.services.type "NodePort" }}
      nodePort: {{ .Values.services.nodeport_http }}
{{- end }}
    - name: https
      port: 443
{{- if eq .Values.services.type "NodePort" }}
      nodePort: {{ .Values.services.nodeport_https }}
{{- end }}
    - name: ssh
      port: 8022
      targetPort: 22
{{- if eq .Values.services.type "NodePort" }}
      nodePort: {{ .Values.services.nodeport_ssh }}
{{- end }}
    - name: salt-publish
      port: 4505
{{- if eq .Values.services.type "NodePort" }}
      nodePort: {{ .Values.services.nodeport_salta }}
{{- end }}
    - name: salt-request
      port: 4506
{{- if eq .Values.services.type "NodePort" }}
      nodePort: {{ .Values.services.nodeport_saltb }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: uyuni-proxy-udp
  namespace: "{{ .Values.namespace }}"
{{- if .Values.services.annotations }}
  annotations:
{{ toYaml .Values.services.annotations | indent 4 }}
{{- end }}
spec:
  selector:
    app: uyuni-proxy
  type: {{ .Values.services.type }}
  ports:
    - name: tftp
      port: 69
      protocol: UDP
{{- if eq .Values.services.type "NodePort" }}
      nodePort: {{ .Values.services.tftp }}
{{- end }}
