name: acceptance-tests-feedback

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request_target:
    paths:
      - 'java/**'
      - 'web/html/src/**'
      - 'testsuite/**'
      - '.github/workflows/acceptance_tests_secondary.yml'
      - '.github/workflows/acceptance_tests_secondary_parallel.yml'
      - '.github/workflows/acceptance_tests_feedback.yml'
      - '.github/workflows/acceptance_tests_common.yml'
      - '!java/*.changes*'
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions-cool/maintain-one-comment@v3
        with:
          body: |
            :wave: Hello! Thanks for contributing to our project.
            Acceptance tests will take some time (aprox. 1h), please be patient :coffee:
            You can see the progress at the end of this page and at https://github.com/uyuni-project/uyuni/pull/${{ github.event.pull_request.number  }}/checks
            Once tests finish, if they fail, you can check :eyes: the cucumber report. See the link at the output of the action.
            You can also check the artifacts section, which contains the logs at https://github.com/uyuni-project/uyuni/pull/${{ github.event.pull_request.number }}/checks.
            
            If you are unsure the failing tests are related to your code, you can check the "reference jobs". These are jobs that run on a scheduled time with code from master. If they fail for the same reason as your build, it means the tests or the infrastructure are broken. If they do not fail, but yours do, it means it is related to your code.
            
            Reference tests:
            
              * https://github.com/uyuni-project/uyuni/actions/workflows/acceptance_tests_secondary_parallel.yml?query=event%3Aschedule
            
              * https://github.com/uyuni-project/uyuni/actions/workflows/acceptance_tests_secondary.yml?query=event%3Aschedule

            KNOWN ISSUES

            Sometimes the build can fail when pulling new jar files from download.opensuse.org . This is a known limitation. Given this happens rarely, when it does, all you need to do is rerun the test. Sorry for the inconvenience.


            For more tips on troubleshooting, see the [troubleshooting guide](https://github.com/uyuni-project/uyuni/wiki/Running-Acceptance-Tests-at-PR#troubleshooting).

            Happy hacking!
            
          body-include: ":warning: You should not merge if acceptance tests fail to pass. :warning:" 

