name: Scheduled Acceptance Tests

on:
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hours
  workflow_dispatch: # Allow manual triggering

jobs:
  scheduled-acceptance-tests:
    name: Acceptance
    if: |
      (github.event_name == 'schedule' && github.repository == 'uyuni-project/uyuni' && github.ref == 'refs/heads/master') || 
      (github.event_name == 'workflow_dispatch')
    uses: ./.github/workflows/acceptance_tests_base.yml
    with:
      tests: "18_run_secondary_tests.sh"
      server_id: "acceptance"
      skip_tests: false
    secrets: inherit

  scheduled-additional-tests:
    name: (${{ matrix.set }}) Additional
    if: |
      (github.event_name == 'schedule' && github.repository == 'uyuni-project/uyuni' && github.ref == 'refs/heads/master') || 
      (github.event_name == 'workflow_dispatch')
    uses: ./.github/workflows/acceptance_tests_base.yml
    strategy:
      fail-fast: false
      matrix:
        set: ['1', '2', '3', '4', '5']
    with:
      tests: "22_run_secondary_parallelizable_tests_subset.sh ${{ matrix.set }}"
      server_id: "additional_${{ matrix.set }}"
      skip_tests: false
    secrets: inherit
