name: Additional Tests
on:
  workflow_call:
    inputs:
      skip:
        required: true
        type: boolean
  repository_dispatch:
    types: [run-additional-tests]

jobs:
  additional-tests:
    name: ${{ matrix.set }}
    if: ${{ github.event_name == 'repository_dispatch' }}
    uses: ./.github/workflows/acceptance_tests_base.yml
    strategy:
      fail-fast: false
      matrix:
        set: ['1', '2', '3', '4', '5']
    with:
      tests: "19_run_secondary_parallelizable_tests_subset.sh ${{ matrix.set }}"
      server_id: "secondary_parallel_${{ matrix.set }}"
      skip: ${{ inputs.skip }}
