name: add_pr_reviewer

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  add_pr_reviewer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
    - name: "Check if there are test framework changes"
      id: review_step
      run: |
        files_modified=`git diff --name-only "origin/$GITHUB_BASE_REF..HEAD" | xargs`
        review=`ruby .github/scripts/needs_qa_squad_review.rb "$files_modified"`
        echo "##[set-output name=review;]$review"
    - name: "Send Review Request to QA Squad"
      if: steps.review_step.outputs.review == 'true' && github.actor == 'srbarrios'
      uses: kunihiko-t/review-request-action@v0.1.3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        reviewers: "atighineanu,maximenoel8,lkotek,ktsamis,Bischoff,calancha"
    - name: "Send Review Request to QA Squad"
      if: steps.review_step.outputs.review == 'true' && github.actor == 'lkotek'
      uses: kunihiko-t/review-request-action@v0.1.3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        reviewers: "atighineanu,maximenoel8,srbarrios,ktsamis,Bischoff,calancha"
    - name: "Send Review Request to QA Squad"
      if: steps.review_step.outputs.review == 'true' && github.actor == 'Bischoff'
      uses: kunihiko-t/review-request-action@v0.1.3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        reviewers: "atighineanu,maximenoel8,lkotek,ktsamis,srbarrios,calancha"
    - name: "Send Review Request to QA Squad"
      if: steps.review_step.outputs.review == 'true' && github.actor == 'ktsamis'
      uses: kunihiko-t/review-request-action@v0.1.3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        reviewers: "atighineanu,maximenoel8,lkotek,srbarrios,Bischoff,calancha"
    - name: "Send Review Request to QA Squad"
      if: steps.review_step.outputs.review == 'true' && github.actor == 'calancha'
      uses: kunihiko-t/review-request-action@v0.1.3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        reviewers: "atighineanu,maximenoel8,lkotek,srbarrios,Bischoff,ktsamis"
    - name: "Send Review Request to QA Squad"
      if: steps.review_step.outputs.review == 'true' && github.actor == 'atighineanu'
      uses: kunihiko-t/review-request-action@v0.1.3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        reviewers: "maximenoel8,lkotek,srbarrios,ktsamis,Bischoff,calancha"
    - name: "Send Review Request to QA Squad"
      if: steps.review_step.outputs.review == 'true' && github.actor == 'maximenoel8'
      uses: kunihiko-t/review-request-action@v0.1.3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        reviewers: "atighineanu,lkotek,srbarrios,ktsamis,Bischoff,calancha"
    - name: "Send Review Request to QA Squad"
      if: steps.review_step.outputs.review == 'true' && github.actor == 'maximenoel8' && github.actor != 'atighineanu' && github.actor != 'ktsamis' && github.actor != 'Bischoff' && github.actor != 'lkotek' && github.actor != 'srbarrios' && github.actor != 'calancha'
      uses: kunihiko-t/review-request-action@v0.1.3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        reviewers: "atighineanu,maximenoel8,lkotek,srbarrios,Bischoff,ktsamis,calancha"
