name: changelog_test

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened, closed]

jobs:
  changelog_test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-ruby@v1
    - name: Run a changelog checker
      run: |
        files_modified=`git diff --name-only "origin/$GITHUB_BASE_REF..HEAD" | xargs`
        ruby .github/scripts/changelog.rb "$files_modified"
        
  changelog_approved:
    if: github.event.action != 'closed'
    needs: changelog_test
    runs-on: ubuntu-latest
    
    steps:
    - name: Changelogs approved
      run : echo "Changelogs approved"

  # warns the user if they merged the PR, but the changelog test failed
  warn_user_if_merged:
    if: always() && github.event.action == 'closed' && github.event.pull_request.merged == true && needs.changelog_test.result == 'failure'
    needs: changelog_test
    runs-on: ubuntu-latest
    steps:
    - name: Remind the author with a comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          :warning: The changelog has not been updated. Please update it @${{ github.event.pull_request.user.login }}.
