name: Automatic frontend lint fix PR

on:
  push:
    branches:
      - master
    paths:
      - 'web/html/src/**'
      - '.github/workflows/frontend-lint-fix-pr.yml'

jobs:
  frontend_lint_fix_pr:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f #v6.1.0
      with:
        node-version: ${{ matrix.node-version }}

    # See https://docs.github.com/en/actions/reference/workflows-and-actions/dependency-caching
    - name: Use cached NPM dependencies
      id: cache-node-modules
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 #v4.3.0
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

    - if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
      name: List cache misses
      continue-on-error: true
      run: npm --prefix web list

    - name: Install production dependencies
      run: npm --prefix web ci --ignore-scripts --save=false

    # Run lint with fixes
    - name: Run lint
      run: npm --prefix web run lint

    # If there's any changes, create a PR, see https://github.com/marketplace/actions/create-pull-request
    - name: Create PR
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e #v7.0.8
      with:
        # Delete the branch after merge
        delete-branch: true
        branch: "automatic-frontend-lint-fix"
        sign-commits: true
        author: "github-actions <github-actions[bot]@users.noreply.github.com>"
        title: "Bot: Fix frontend lint issues"
        body: |
          ## What does this PR change?

          This is a bot generated pull request. It appears fixable lint issues were found in master, you were tagged for a review as you were the last one to merge.  

          If this PR was made in error, please reach out to [@uyuni-project/frontend](https://github.com/orgs/uyuni-project/teams/frontend).  

          ## Changelogs

          The applied changes are only stylistic and do not need a changelog.

          - [x] No changelog needed
        commit-message: "Bot: Fix frontend lint issues"
        # Ask for a review from the user who triggered the run, in this case the person who pushed to master
        reviewers: ${{ github.actor }}
