name: Frontend unit tests

on:
  push:
    branches:
      - master
    paths:
      - 'web/html/src/**'
      - '.github/workflows/frontend-unit-tests.yml'
  pull_request:
    paths:
      - 'web/html/src/**'
      - '.github/workflows/frontend-unit-tests.yml'

jobs:
  frontend_unit_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 #v6.0.0
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install production dependencies
      run: npm --prefix web ci --ignore-scripts --save=false

    - name: Run tests
      run: npm --prefix web run test -- --no-cache
      env:
        BABEL_ENV: 'test'
