name: Frontend Typescript compilation

on:
  push:
    branches:
      - master
    paths:
      - 'web/html/src/**'
      - '.github/workflows/frontend-typescript-compilation.yml'
  pull_request:
    paths:
      - 'web/html/src/**'
      - '.github/workflows/frontend-typescript-compilation.yml'

jobs:
  frontend_typescript_compilation:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 #v6.0.0
      with:
        node-version: ${{ matrix.node-version }}

    # See https://docs.github.com/en/actions/reference/workflows-and-actions/dependency-caching
    - name: Use cached NPM dependencies
      id: cache-node-modules
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 #v4.3.0
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

    - if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
      name: List cache misses
      continue-on-error: true
      run: npm --prefix web list

    - name: Install production dependencies
      run: npm --prefix web ci --ignore-scripts --save=false

    - name: Compile Typescript
      run: npm --prefix web run tsc
