name: Frontend dependency audit

on:
  # This is intentionally not run on `pull_request` since we don't want to block unrelated PRs with fresh audit issues
  push:
    branches:
      - master
    paths:
      - 'web/html/src/package.json'
      - '.github/workflows/frontend-dependency-audit.yml'

jobs:
  frontend_dependency_audit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f #v6.1.0
      with:
        node-version: ${{ matrix.node-version }}

    # See https://docs.github.com/en/actions/reference/workflows-and-actions/dependency-caching
    - name: Use cached NPM dependencies
      id: cache-node-modules
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 #v4.3.0
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

    - if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
      name: List cache misses
      continue-on-error: true
      run: npm --prefix web list

    # We only install production dependencies here to simulate a situation similar to OBS/IBS
    - name: Install production dependencies
      run: npm --prefix web ci --ignore-scripts --save=false --omit=dev

    # Audit will exit with non-zero if there are any vulnerabilities, whoever triggered the run will get an email by default
    - name: Run audit
      run: npm --prefix web run audit-production-dependencies
