name: Javascript build

on:
  push:
    branches:
      - master
    paths:
      - 'web/html/src/**'
      - '.github/workflows/javascript-build.yml'
  pull_request:
    paths:
      - 'web/html/src/**'
      - '.github/workflows/javascript-build.yml'
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  javascript_build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e #v4.3.0
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get Yarn cache directory
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Use Yarn cache
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf #v4.2.2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}

    # We only install production dependencies here to simulate a situation similar to OBS/IBS
    - name: Install production dependencies
      run: yarn install --force --ignore-optional --production=true --frozen-lockfile --prefer-offline

    - name: Build application
      run: yarn build

    # See https://github.com/mxschmitt/action-tmate?tab=readme-ov-file#only-on-failure
    - name: Setup tmate session
      if: ${{ failure() && github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      uses: mxschmitt/action-tmate@c606f8612a802e46b3742322514c09fbc8c4afee #v3.21
      with:
        limit-access-to-actor: true
