name: Java Microservices Maven Build

on:
  push:
    branches:
      - master
    paths:
      - 'microservices/**'
      - '.github/workflows/java-microservices-mvn-build.yml'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'microservices/**'
      - '.github/workflows/java-microservices-mvn-build.yml'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
      - name: Set up JDK 17
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 #v5.2.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install and verify uyuni-java-parent
        run: >
          mvn -B --no-transfer-progress --file microservices/uyuni-java-parent/pom.xml --non-recursive install checkstyle:check

      - name: Install and verify uyuni-java-common
        run: >
          mvn -B --no-transfer-progress --file microservices/uyuni-java-common/pom.xml install checkstyle:check

      - name: Install and verify coco-attestation
        run: >
          mvn -B --no-transfer-progress --file microservices/coco-attestation/pom.xml install checkstyle:check
