name: Java checkstyle

on:
  push:
    branches:
      - master
    paths:
      - 'java/**.java' 
  pull_request:
    paths:
      - 'java/**.java'

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/systemsmanagement/uyuni/master/docker/containers/uyuni-master-pgsql:latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v2
      with:
        path: java/lib
        key: ${{ runner.os }}-java-lib-${{ hashFiles('java/buildconf/ivy/*.*') }}

    - name: Resolve dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        ant -f java/manager-build.xml ivy

    - name: Run checkstyle
      run: ant -f java/manager-build.xml checkstyle
