name: RuboCop

on:
  pull_request:
    paths:
      - '.github/workflows/rubocop.yml'
      - 'testsuite/features/**.rb'
      - 'testsuite/.rubocop.yml'
      - 'testsuite/.rubocop_todo.yml'
      - 'testsuite/Gemfile'
      - 'testsuite/Rakefile'

jobs:
  rubocop:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
    - uses: ruby/setup-ruby@2a7b30092b0caf9c046252510f9273b4875f3db9 # v1.254.0
      with:
        ruby-version: '3.3'

    - name: Install Rubocop
      run: |
        gem install rubocop -v 1.65.1

    - name: Run RuboCop
      run: |
        cd testsuite
        rubocop features/*
