name: RuboCop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - '.github/workflows/rubocop.yml'
      - 'testsuite/features/**.rb'
      - 'testsuite/.rubocop.yml'
      - 'testsuite/.rubocop_todo.yml'

jobs:
  rubocop:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.5'

    - name: Install Rubocop
      run: |
        gem install parallel -v 1.10
        gem install parser -v 3.0.0.0
        gem install rainbow -v 2.2.2
        gem install regexp_parser -v 1.8
        gem install rexml
        gem install rubocop-ast -v 1.7.0
        gem install ruby-progressbar -v 1.7
        gem install unicode-display_width -v 1.4.0
        gem install rubocop -v 1.17.0

    - name: Run RuboCop
      run: |
        cd testsuite
        rubocop features/*
