name: RuboCop

on:
  pull_request:
    paths:
      - '.github/workflows/rubocop.yml'
      - 'testsuite/features/**.rb'
      - 'testsuite/.rubocop.yml'
      - 'testsuite/.rubocop_todo.yml'
      - 'testsuite/Gemfile'
      - 'testsuite/Rakefile'

jobs:
  rubocop:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
    - uses: ruby/setup-ruby@4c24fa5ec04b2e79eb40571b1cee2a0d2b705771 #v1.278.0
      with:
        ruby-version: '4.0'

    - name: Install and Run RuboCop
      run: |
        cd testsuite
        gem install bundler
        bundle install
        bundle exec rubocop --version
        bundle exec rubocop features/*
