name: RuboCop

on:
  pull_request:
    paths:
      - 'testsuite/features/**.rb'

jobs:
  rubocop:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5'

    - name: Install RuboCop
      run: gem install rubocop -v 0.84.0

    - name: Run RuboCop
      run: |
        cd testsuite
        rubocop features/*
