name: Ruby checkstyle

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  ruby_checkstyle:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5'

    - name: Install RuboCop
      run: gem install rubocop -v 0.84.0
      
    - name: Run RuboCop
      run: |
        cd testsuite
        rubocop features/*
