name: Check the content of Salt SLS files

on:
  pull_request:
    paths: 'susemanager-utils/susemanager-sls/salt/**/*.sls'

jobs:
  salt_sls_files_checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
    - name: module.run must be absent
      run: "! grep --fixed-strings module.run susemanager-utils/susemanager-sls/salt/**/*.sls"
