name: Check the content of Salt SLS files

on:
  pull_request:
    paths: 'susemanager-utils/susemanager-sls/salt/**/*.sls'

jobs:
  salt_sls_files_checks:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4.2.2

    - uses: mattsb42/not-grep@master
      with:
        config-file: ./.github/config/file-content-checks.toml
        # If you don't set debug, passing checks will be hidden.
        debug: true
