name: Check the content of Salt SLS files

on:
  pull_request:
    paths: 'susemanager-utils/susemanager-sls/salt/**/*.sls'

jobs:
  salt_sls_files_checks:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1

    - uses: mattsb42/not-grep@6830ab112798c6561640e1a3372e65f0bcb9435a #master
      with:
        config-file: ./.github/config/file-content-checks.toml
        # If you don't set debug, passing checks will be hidden.
        debug: true
