name: Check the content of Salt SLS files

on:
  pull_request:
    paths: 'susemanager-utils/susemanager-sls/salt/**/*.sls'

jobs:
  salt_sls_files_checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
    - name: module.run must be absent
      run: "! grep --fixed-strings module.run susemanager-utils/susemanager-sls/salt/**/*.sls"
