name: 'Suggested tests to cover this Pull Request'

on:
  pull_request_target:
    paths:
      - '**.java'

jobs:
  tests-covering-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm i ioredis
      - id: files
        uses: Ana06/get-changed-files@v2.3.0
        with:
          filter: '*.java'
      - id: tests_covering_pr
        name: Tests covering PR
        env:
          REDIS_USER: ${{ secrets.REDIS_USER }}
          REDIS_PASS: ${{ secrets.REDIS_PASS }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
        run: echo "result=$(node .github/scripts/test_covering_pr.js ${{ steps.files.outputs.added_modified }})" >> $GITHUB_OUTPUT
      - id: debugme
        name: debug
        env:
          REDIS_USER: ${{ secrets.REDIS_USER }}
          REDIS_PASS: ${{ secrets.REDIS_PASS }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
        run: echo "result=$(node .github/scripts/test_covering_pr.js ${{ steps.files.outputs.added_modified }})"

      - name: Write a comment into the Pull Request
        uses: actions-cool/maintain-one-comment@v3
        with:
          body: |
            ${{ steps.tests_covering_pr.outputs.result }}
          body-include: '<suggested_tests>'
