name: Generate YARD Documentation

on:
  push:
    branches:
      - master

jobs:
  generate_documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Set up Ruby
        uses: ruby/setup-ruby@efbf473cab83af4468e8606cc33eca9281bb213f #v1.256.0
        with:
          ruby-version: '3.3'

      - name: Install dependencies
        run: |
          sudo apt-get install -y rdoc
          gem install yard yard-cucumber

      - name: Generate .yard/config
        run: |
          mkdir $HOME/.yard
          echo '--- !ruby/hash-with-ivars:SymbolHash
          elements:
            :load_plugins: true
            :ignored_plugins: []
            :autoload_plugins: []
            :safe_mode: false
            :"yard-cucumber":
              language:
                step_definitions: [ "Given", "When", "Then", "And", "But"]
              menus: [ "features", "directories", "tags", "steps", "step definitions" ]
          ivars:
            :@symbolize_value: false%' > $HOME/.yard/config

      - name: Generate YARD Documentation
        run: |
          cd testsuite
          yard doc --protected --private features/step_definitions/*.rb features/support/*.rb features/support/**/*.rb features/**/*.feature features/**/**/*.feature

      - name: Archive documentation as artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 #v4.6.1
        with:
          name: yard-docs
          path: testsuite/doc
